FROM python:3.6-slim

WORKDIR locust
COPY locust/files ./files
COPY locust/secondary_analysis.py .

RUN pip install locust

ENV AUTH_BROKER_URL=http://localhost:8888/auth
ENV CLIENT_ID=0
ENV CLIENT_SECRET=0

ENV FILE_UPLOAD_URL=http://localhost:8888/v1
ENV HOST_URL=http://localhost:8080

EXPOSE 8089
CMD locust --host=${HOST_URL} -f secondary_analysis.py