apiVersion: v1
kind: Secret
metadata:
  name: auth-broker
data:
  client-id: PHJlZGFjdGVkPg==
  client-secret: PHJlZGFjdGVkPg==

---

apiVersion: v1
kind: Pod
metadata:
  name: submission
  labels:
    app.kubernetes.io/name: submission
    app.kubernetes.io/part-of: scale-testing
spec:
  containers:
  - name: submission
    image: humancellatlas/ingest-scale-test-submission:e95fced
    ports:
    - containerPort: 8089
    env:
    - name: HOST_URL
      value: http://api.ingest.testing.data.humancellatlas.org
    - name: AUTH0_DOMAIN
      value: danielvaughan.eu.auth0.com
    - name: CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: auth-broker
          key: client-id
    - name: CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: auth-broker
          key: client-secret